name: random_lunch
description: Flutter app generating random lunch
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  flutter_config: ^2.0.0
  logger: ^1.1.0
  bloc: ^8.0.3
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  auto_route: ^4.0.1
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  mockito: ^5.1.0
  bloc_test: ^9.0.3
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true
